#! /usr/bin/env bash

set -x
set -euo pipefail

# minasearch-prod-blue
TARGET='root@172.232.152.58'

# minasearch-prod-green
# TARGET='root@172.234.120.192'

scp *.nix ../*.nix "$TARGET":
scp ~/Sync/crit/keys/granola-cloudflare-minasearch-creds-json "$TARGET":/run/keys/granola-cloudflare-minasearch-creds-json
ssh "$TARGET" "
  chown bk:keys /run/keys/granola-cloudflare-minasearch-creds-json &&
  chmod 0400 /run/keys/granola-cloudflare-minasearch-creds-json &&
  :
"
ssh "$TARGET" "
  echo "${BUILDKITE_AGENT_TOKEN}" > /run/keys/buildkite-agent-token &&
  chown bk:keys /run/keys/buildkite-agent-token &&
  chmod 0400 /run/keys/buildkite-agent-token &&
  echo "${LINODE_OBJ_ACCESS_KEY}" > /run/keys/linode-access-key &&
  chown bk:keys /run/keys/linode-access-key &&
  chmod 0400 /run/keys/linode-access-key &&
  echo "${LINODE_OBJ_SECRET_KEY}" > /run/keys/linode-secret-key &&
  chown bk:keys /run/keys/linode-secret-key &&
  chmod 0400 /run/keys/linode-secret-key &&
  :
"
ssh "$TARGET" "
  systemctl stop buildkite-agent.service
  nixos-rebuild switch -I nixos-config=config.nix &&
  nixos-rebuild boot -I nixos-config=config.nix &&
  :
"
