#! /usr/bin/env bash

set -x
set -euo pipefail

# minasearch-prod-blue
# TARGET='root@172.232.152.58'

# minasearch-prod-green
TARGET='root@172.234.120.192'

scp *.nix ../*.nix "$TARGET":
ssh "$TARGET" "
  nix-channel --add https://channels.nixos.org/nixos-24.11 nixos &&
  nix-channel --update &&
  nixos-rebuild build -I nixos-config=config.nix --upgrade &&
  :
"
ssh "$TARGET" "
  systemctl stop buildkite-agent.service
  nixos-rebuild switch -I nixos-config=config.nix --upgrade &&
  nixos-rebuild boot -I nixos-config=config.nix --upgrade &&
  :
"
