#! /usr/bin/env bash

set -x
set -euo pipefail

TARGET='root@172.232.140.52'

scp *.nix ../*.nix "$TARGET":
ssh "$TARGET" "
  nix-channel --add https://channels.nixos.org/nixos-24.11 nixos &&
  nix-channel --update &&
  nixos-rebuild build -I nixos-config=config.nix --upgrade &&
  :
"
ssh "$TARGET" "
  systemctl stop buildkite-agent.service
  nixos-rebuild switch -I nixos-config=config.nix --upgrade &&
  nixos-rebuild boot -I nixos-config=config.nix --upgrade &&
  systemctl start buildkite-agent.service
  :
"
