#! /usr/bin/env bash

set -x
set -euo pipefail

TARGET='root@172.232.139.106'

scp *.nix "$TARGET":
ssh "$TARGET" "nixos-rebuild switch -I nixos-config=config.nix &&
  nixos-rebuild boot -I nixos-config=config.nix"
