#! /usr/bin/env bash

set -x
set -euo pipefail

TARGET='root@172.232.148.166'

scp *.nix ../*.nix flake.lock "$TARGET":
ssh "$TARGET" "
  systemctl stop buildkite-agent.service
  echo ${BUILDKITE_AGENT_TOKEN} > /run/keys/buildkite-agent-token &&
  nixos-rebuild switch -I nixos-config=config.nix --flake .#nixos &&
  chown bk:keys /run/keys/buildkite-agent-token &&
  chmod 0400 /run/keys/buildkite-agent-token &&
  nixos-rebuild boot -I nixos-config=config.nix --flake .#nixos &&
  :
"
