#! /usr/bin/env bash

set -x
set -euo pipefail

TARGET='root@172.234.120.192'

scp *.nix "$TARGET":
ssh "$TARGET" "
  systemctl stop buildkite-agent.service
  echo ${BUILDKITE_AGENT_TOKEN} > /run/keys/buildkite-agent-token &&
  echo ${CLOUDFLARE_ACCOUNT_ID} > /run/keys/cloudflare-account-id &&
  echo ${CLOUDFLARE_API_TOKEN} > /run/keys/cloudflare-api-token &&
  nixos-rebuild switch -I nixos-config=config.nix &&
  chown bk:keys /run/keys/buildkite-agent-token &&
  chown bk:keys /run/keys/cloudflare-account-id &&
  chown bk:keys /run/keys/cloudflare-api-token &&
  chmod 0400 /run/keys/buildkite-agent-token &&
  chmod 0400 /run/keys/cloudflare-account-id &&
  chmod 0400 /run/keys/cloudflare-api-token &&
  nixos-rebuild boot -I nixos-config=config.nix &&
  :
"
