#! /usr/bin/env bash

set -x
set -euo pipefail

# granola-prod
TARGET='root@172.234.120.192'

scp *.nix ../*.nix "$TARGET":
ssh "$TARGET" "
  systemctl stop buildkite-agent.service
  nix-channel --update &&
  nixos-rebuild build -I nixos-config=config.nix --upgrade &&
  nixos-rebuild switch -I nixos-config=config.nix --upgrade &&
  nixos-rebuild boot -I nixos-config=config.nix --upgrade &&
  :
"
